name: Frontend CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: '--openssl-legacy-provider'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: ./Projekt_Frontend

      - name: Build
        run: npm run build
        working-directory: ./Projekt_Frontend

      - name: Run Tests
        run: |
          echo "Hier teste ich"
          echo "Tests erfolgreich"
        working-directory: ./Projekt_Frontend

      - name: Deploy
        run: |
          echo "Hier deploye ich"
          echo "Deployment erfolgreich"
        working-directory: ./Projekt_Frontend
